### ISSUE TITLE
give feedback

### ISSUE THREAD

**Issue by boomt1337** [boomt1337/betabot#1]
leave comments on todos or feedback regarding the code (discord/node.js masters only) or feature requests

current todo:
learn node
learn swift
Mute
Serverinfo
About
much more

**Comment by Someonewhoisaperson** [comment]
hi

**Comment by Someonewhoisaperson** [comment]
for kick ban and mute please make it so that the bot can find partial usernames insted of full ping

**Comment by Someonewhoisaperson** [comment]
also when i use &ban it comes up with the succses message even if it fails
